spring.application.name=Berserkdle

spring.datasource.url=jdbc:postgresql://localhost:5432/berserkdle
spring.datasource.name=berserkdle
spring.datasource.password=postgres
spring.datasource.username=postgres
